# version: "3.9"  # optional since v1.27.0
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: aleksod/recordr
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace